service: dawn

provider:
  name: aws
  runtime: python3.6
  region: ${env:AWS_REGION}
  timeout: 60
  memorySize: 128
  environment:
    tagKey: dawn

  iamRoleStatements:
  - Effect: Allow
    Action:
      - ec2:DescribeInstances
      - ec2:DescribeTags
      - ec2:StartInstances
      - ec2:StopInstances
    Resource: "*"

functions:
  start:
    handler: start.handle
    events:
    - schedule:
        rate: cron(0 9 ? * * *)

  stop:
    handler: stop.handle
    events:
    - schedule:
        rate: cron(0 17 ? * * *)
